[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
tokio = "1.34.0"
colored = "2.0.4"
log = "0.4.20"
fern = "0.6.2"
chrono = "0.4.31"